language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - $ANDROID_API

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-$ANDROID_TARGET-$ANDROID_API
env:
  global:
    - ANDROID_DIR=Client/Client.Android
    - ANDROID_APP1_NAME=DemoApp1
    - ANDROID_APP2_NAME=DemoApp2
    - ANDROID_TARGET=armeabi-v7a # x86 or armeabi-v7a. At this time, Travis can not run android-x86
    - ANDROID_API=android-22
    # - NODE_JS_APP_NAME=N/A
  matrix:
    # Use these env variables to run test on Travis:
    #   ANDROID_APP1
    #   ANDROID_APP2
    #   NODE_JS_SERVER
    # Format: <en variable>=<test suite name>
    - ANDROID_APP1=connectedCheck
    - ANDROID_APP2=connectedCheck
    # - NODE_JS_SERVER=connectedCheck

    # Test for multiple platform
    # - ANDROID_API=22 ANDROID_TARGET=x86
    # - ANDROID_API=19 ANDROID_TARGET=armeabi-v7a
    # - ANDROID_API=22 ANDROID_TARGET=armeabi-v7a
before_script:
  - chmod -R ugo+x travis-script/
  - ./travis-script/run-emulator.sh
script:
  # Run infer test
  - wget https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux -O opam
  - chmod +x opam
  - ./opam init --yes --comp=4.01.0 #(then say 'y' to the final question)
  - eval `./opam config env`
  - ./opam install --yes sawja.1.5 atdgen.1.5.0 javalib.2.3a extlib.1.5.4 #(then say 'y' to the question)
  
  - git clone https://github.com/facebook/infer.git
  - cd infer/
  - make -C infer java
  - export PATH=`pwd`/infer/bin:$PATH
  - cd ..
  
  - infer -- ./Client/Client.Android/DemoApp1/gradlew build
  - infer -- ./Client/Client.Android/DemoApp2/gradlew build
  # Run test cases
  - ./travis-script/run-tests.sh
