language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    # - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19
env:
  matrix:
    - ANDROID_API=19 ANDROID_TARGET=x86
    - ANDROID_API=22 ANDROID_TARGET=x86
    - ANDROID_API=19 ANDROID_TARGET=armeabi-v7a
    - ANDROID_API=22 ANDROID_TARGET=armeabi-v7a
script:
  - cd Client/DemoCI
  - ./gradlew build connectedCheck
